version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # ports:
    #   - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 19092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://sputil.int.thelintons.ca:19092
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    depends_on:
      - kafka
    ports:
      - 18080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=flow
      - POSTGRES_PASSWORD=uyrT1hM72cecTTu6
      - POSTGRES_DB=flow_results

  stage1:
    build:
      context: ./src/python_math
      dockerfile: Dockerfile
    container_name: flow_stage1
    depends_on:
      - kafka
    environment:
      - OPERATION_TYPE=add
      - BOOTSTRAP_SERVERS=kafka:9092
      - INPUT_TOPIC=stage1
      - OUTPUT_TOPIC=stage2
      - DB_HOST=postgres
      - DB_NAME=flow_results
      - DB_USER=flow
      - DB_PASSWORD=uyrT1hM72cecTTu6

  stage2:
    build:
      context: ./src/python_math
      dockerfile: Dockerfile
    container_name: flow_stage2
    depends_on:
      - kafka
    environment:
      - OPERATION_TYPE=multiply
      - BOOTSTRAP_SERVERS=kafka:9092
      - INPUT_TOPIC=stage2
      - OUTPUT_TOPIC=stage3
      - DB_HOST=postgres
      - DB_NAME=flow_results
      - DB_USER=flow
      - DB_PASSWORD=uyrT1hM72cecTTu6

  stage3:
    build:
      context: ./src/go_lcm
      dockerfile: Dockerfile
    container_name: flow_stage3
    depends_on:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - INPUT_TOPIC=stage3
      - OUTPUT_TOPIC=stage4
      - DB_HOST=postgres
      - DB_NAME=flow_results
      - DB_USER=flow
      - DB_PASSWORD=uyrT1hM72cecTTu6

  stage4:
    build:
      context: ./src/python_roman
      dockerfile: Dockerfile
    container_name: flow_stage4
    depends_on:
      - kafka
    environment:
      - OPERATION_TYPE=multiply
      - BOOTSTRAP_SERVERS=kafka:9092
      - DB_HOST=postgres
      - DB_NAME=flow_results
      - DB_USER=flow
      - DB_PASSWORD=uyrT1hM72cecTTu6

